# -*- coding: utf-8 -*-
"""Helix Test.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T69ZHMB_FdCREGGdC9BaNeSX5nF5hG0K
"""

!git clone https://github.com/PavanMohanN/bliq.git

cd bliq

pip install -e .

import torch
from bliq.model import BLiqNet
print("Success!")

import torch
import numpy as np
from bliq.model import BLiqNet
from bliq.utils import compute_metrics, plot_liquid_constants

def generate_helix_data(n=2000):
    # Target: 1D (Phase/Height)
    y = torch.linspace(0, 4 * np.pi, n).view(-1, 1)

    # Input: 3D (Helix Coordinates)
    x1 = torch.cos(y)
    x2 = torch.sin(y)
    x3 = y / (4 * np.pi) # Normalized height
    x = torch.cat([x1, x2, x3], dim=1)

    return x, y

# 1. Setup Data (3D -> 1D)
x, y = generate_helix_data()

# 2. Initialize General Purpose BLiqNet
# input_dim=3, output_dim=1
model = BLiqNet(input_dim=3, output_dim=1, hidden_dim=128, t_span=(0.0, 2.0))

# 3. Train
print("Training BLiqNet on 3D Helix...")
model.fit(x, y, epochs=1000, lambda_inv=2.0, lambda_rec=0.01)

# 4. Verification
with torch.no_grad():
    y_pred = model.forward(x)
    # Testing Stochastic Inverse (sampling 5 points on the helix)
    x_rec = model.inverse(y, noise_level=0.1)

r2, rmse = compute_metrics(y, y_pred)
print(f"\nVerification Results:")
print(f"Forward R2: {r2:.4f} (Target > 0.99)")
print(f"Forward RMSE: {rmse:.4f}")

# 5. Check 'Liquid' Behavior
plot_liquid_constants(model)

